### ISSUE TITLE
heatmapgl TODO list

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1080]
Before getting merged into the main plotly.js dist bundle, we need to make sure following problems are addressed
- [x] `heatmapgl` test-images are not reproducible. Maybe this is just a matter of bumping the `gl-shader` requirement.
- [x] top-most and right-most points aren't being catch by the hover picking routine

![gifrecord_2016-10-25_093142](https://cloud.githubusercontent.com/assets/6675409/19688038/e90be7ce-9a95-11e6-8ba6-61a7870b36e9.gif)
- [x] double-check that we are handling `NaN`s correctly. One good test would be to `Plotly.restyle(gd, 'type', 'heatmapgl')` all our heatmap test mocks.
- [x] include only attributes that are relevant to the `gl2d` version (instead of simply copying the `heatmap` attributes). For example, `heatmapgl` doesn't support `zsmooth`, `xgap` and `ygap`.

See the [`heatmapgl-primetime`](https://github.com/plotly/plotly.js/compare/heatmapgl-primetime) branch for more some WIP work.

**Comment by etpinard** [comment]
Maybe @dfcreative would be interested in looking some of the items :arrow_double_up: ?

cc @monfera @jackparmer

**Comment by dfcreative** [comment]
Sure!

**Comment by jackparmer** [comment]
That would be awesome @dfcreative ! Want to come by the office for lunch this Friday?

**Comment by dfcreative** [comment]
@jackparmer sure!

**Comment by dfcreative** [comment]
Ok, as for 
> top-most and right-most points aren't being catch

that seems to be wrongly rendered `pickBuffer`:
![image](https://cloud.githubusercontent.com/assets/300067/19818341/65f01e02-9d1d-11e6-868a-a726b45cb32c.png)

only 9 levels out of 10 are here

**Comment by dfcreative** [comment]
> test-images are not reproducible

All the difference I see is in fonts rendering,

original:
![image](https://cloud.githubusercontent.com/assets/300067/19819674/9e181996-9d23-11e6-903d-5d20c1daba48.png)

result:
![image](https://cloud.githubusercontent.com/assets/300067/19819664/924dcb7e-9d23-11e6-8beb-0011a3107119.png)

could you elaborate @etpinard?

**Comment by etpinard** [comment]
@dfcreative It's similar to https://github.com/plotly/streambed/issues/6307#issuecomment-231818023

Generating one `heatmapgl` mock at a time works fine. But inside a loop, image generation is off.

**Comment by dfcreative** [comment]
Ok, the problem of top-right points is in [this line](https://github.com/gl-vis/gl-heatmap2d/blob/master/heatmap.js#L249), which ignores edge vertices. It is easily fixable for the x axis by adding `dx`, but difficult for the y axis, because pick shader interpolates value.
A fact that `pickBuffer` in some magic way transforms float array of ids into `vec4`s of ints adds to the complexity of issue.

**Comment by dfcreative** [comment]
Ok, top-most and right-most picking problem should be fixed by https://github.com/gl-vis/gl-heatmap2d/pull/2

**Comment by jackparmer** [comment]
Hey @dfcreative - Do you have an idea for this one by chance?

> heatmapgl test-images are not reproducible. Maybe this is just a matter of bumping the gl-shader requirement.

What do you think is your timeline for the other 2?

**Comment by dfcreative** [comment]
@jackparmer all heatmap related tests are reproduced fine on my machine, I guess I should discuss that with @etpinard this friday, to see the issue in action to understand what's wrong.

**Comment by dfcreative** [comment]
@etpinard ok, last https://github.com/gl-vis/gl-heatmap2d/pull/2 should fix the images/picking issues

**Comment by etpinard** [comment]
@dfcreative nice job. Your patch even works on CI:

![image](https://cloud.githubusercontent.com/assets/6675409/20313727/d08c5c60-ab25-11e6-84dd-bef3ab5f991f.png)

The first two items are :white_check_mark:

**Comment by etpinard** [comment]
Oh. I spoke too soon. Picking is still broken for a few other mocks.

For example, [`Earth_heatmap`](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/Earth_heatmap.json) when replace `data[0].type`  from `'heatmap'` to `'heatmapgl'`:

![gifrecord_2016-11-15_114210](https://cloud.githubusercontent.com/assets/6675409/20314569/a1929b56-ab28-11e6-9cb8-051e481f2cd1.gif)

**Comment by etpinard** [comment]
Same story for the [`4`](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/4.json) mock:

![gifrecord_2016-11-15_114345](https://cloud.githubusercontent.com/assets/6675409/20314637/da89b2f0-ab28-11e6-9439-ac73b946d7e7.gif)

**Comment by dfcreative** [comment]
@etpinard https://github.com/gl-vis/gl-heatmap2d/pull/2/commits/04cae767bf14444fe236369011e1c414509ea533 should fix picking, tested on various mocks. My render of `4.json` is different though, I guess because of custom layout options
![image](https://cloud.githubusercontent.com/assets/300067/20444690/070a32e0-ada0-11e6-923e-80af5c2c866e.png). Should it be fixed?

**Comment by etpinard** [comment]
@dfcreative thanks. I'll give it a test :car: on Monday.

**Comment by etpinard** [comment]
@dfcreative with your last commit, this is looking really good. I'll spend a few more minutes double-check, but looks like we're really to something mergeable. :beers:
