### ISSUE TITLE
Support adding text labels to lines and shapes

### ISSUE THREAD

**Issue by emilykl** [plotly/plotly.js#6430]
# Text on Shapes feature

Expand the Shape API to support adding a text label to any line or shape.

Labels can be styled similarly to text annotations, and support options for setting their position relative to the shape or line. 

# Proposed API

Here is the proposed API for Text on Shapes, as discussed with @alexcjohnson :

- `label` : Top-level property to be added to `shape`, holding all label options
    - `text` : The label’s text
    - `font` : The label’s font properties (same properties as for Annotation)
        - `color`
        - `family`
        - `size`
    - `position` : The label’s position relative to the shape. Possible values: `[ left | center | right ] [ top | middle | bottom ]` ; OR `[ start | end ]` for lines
    - `textangle` : Rotation angle of the label. Possible values : number between -180 and 180 ; OR `[ auto ]` for lines (same angle as line)
    - `xanchor` : The x-component of the anchor point on the label used to determine position (in the pre-rotated reference frame). Possible values : `[ left | center | right ]`
    - `yanchor` : The y-component of the anchor point on the label used to determine position (in the pre-rotated reference frame). Possible values : `[ top | middle | bottom ]`
    - `padding` : Offset of label relative to `xanchor` and `yanchor` (symmetrical on all sides)

cc @alexcjohnson @archmoj 

_Revised 10 Jan 2023: Changed `angle` property name to `textangle`_

# To-dos

- [x] Add above properties to shape attributes
- [x] Implement basic functionality of rendering text relative to shape position
- [x] Properly handle re-render on pan/zoom 
- [x] Properly handle re-render on shape move
- [x] Implement `xanchor`
- [ ] Implement `yanchor`
- [x] Implement `padding`
- [x] Implement `position`
- [x] Implement `textangle`
  - [x] Numeric angles
  - [x] `auto` angle for lines
- [x] Implement `font`
- [ ] Correctly handle multiline labels
- [x] Correctly handle clipping outside plot area
- [ ] Properly set defaults for all properties
- [ ] Add image test
- [ ] Add Jasmine test

## Partnership

Development of this feature is sponsored by Volkswagen's Center of Excellence for Battery Systems.

<p float="left" align="center" >
<img src="https://user-images.githubusercontent.com/42301846/207075484-2c77d1e1-f0b5-43da-89bf-66ac73c50007.png" width=40% aspect-ratio=3/10 >
</p>

**Comment by emilykl** [comment]
Quick comparison of the above to the `annotations` API: 
- The properties `text`, `font`, `xanchor`, and `yanchor` have the same names and functions for annotations
    - Note: `xanchor` and `yanchor` support the value `auto` in addition; worth considering whether we should add `auto` as a value for `xanchor` and `yanchor` here (although the `auto` behavior would probably be different)
- `angle` is called `textangle` for annotations — should we change the name here for consistency?
- `position` and `padding` don't really have equivalents for annotations (annotations have `borderpad`, but that's specifically for border appearance)
